### ISSUE TITLE
Change project structure

### ISSUE THREAD

**Issue by norbertgal97** [BME-MIT-IET/anyapicifiai-iet-2019#12]
Changing project structure to Maven

**Comment by mrdeakd** [comment]
Commit : https://github.com/BME-MIT-IET/anyapicifiai-iet-2019/pull/14/commits/6df7ff409547aeb9c369ce570f8152effb573a19
Following the project structure of Maven

**Comment by norbertgal97** [comment]
The structure of project is suitable for Maven.
