### ISSUE TITLE
Add junit to pom.xml

### ISSUE THREAD

**Issue by norbertgal97** [BME-MIT-IET/anyapicifiai-iet-2019#13]
Adding junit dependency to Maven's pom.xml

**Comment by mrdeakd** [comment]
Commit : https://github.com/BME-MIT-IET/anyapicifiai-iet-2019/commit/69708eef28e2a0a2004cf0e2517c45c747a06259
Junit dependency with a basic test

**Comment by norbertgal97** [comment]
Checked, it is ok.
