### ISSUE TITLE
Identify issues through static code analysis using Codacy

### ISSUE THREAD

**Issue by mrdeakd** [BME-MIT-IET/anyapicifiai-iet-2019#18]
We should have a look at on the problems.

**Comment by norbertgal97** [comment]
Commit: [eecf0cb](https://github.com/BME-MIT-IET/anyapicifiai-iet-2019/commit/eecf0cbe37d3b03b61dd61159c790d8b398a5864)
Visibility of variables changed to private

**Comment by feheragnes** [comment]
There are no more privacy issues according to Codacy. Nice work @norbertgal97!

**Comment by feheragnes** [comment]
I think the last issue according to Codacy (Avoid throwing raw exception types) is not really a problem, the code is sufficient.
