### ISSUE TITLE
Use Codacy CI in the project

### ISSUE THREAD

**Issue by mrdeakd** [BME-MIT-IET/anyapicifiai-iet-2019#2]
Have a look at on Codacy and the issues using this project.

**Comment by feheragnes** [comment]
Added the project to [app.codacy.com](url)

**Comment by feheragnes** [comment]
Current issues: [link](https://app.codacy.com/app/feheragnes/anyapicifiai-iet-2019/issues/index?bid=12465148)

**Comment by feheragnes** [comment]
No more important issues.
