### ISSUE TITLE
Make unit tests

### ISSUE THREAD

**Issue by NomarCub** [BME-MIT-IET/anyapicifiai-iet-2019#24]
Improve stability and code coverage

**Comment by NomarCub** [comment]
https://github.com/BME-MIT-IET/anyapicifiai-iet-2019/commit/a9ae2b60a950efa682d1421928af08d839c7c965

**Comment by mrdeakd** [comment]
https://github.com/BME-MIT-IET/anyapicifiai-iet-2019/pull/25 was pulled

**Comment by NomarCub** [comment]
more tests added in https://github.com/BME-MIT-IET/anyapicifiai-iet-2019/commit/1f58055f30372c923bba6fe28976b505ef764fa6

**Comment by NomarCub** [comment]
Exception tests added in https://github.com/BME-MIT-IET/anyapicifiai-iet-2019/commit/33f181b7f2e0659b027bba71d6e820835e3e2616

**Comment by NomarCub** [comment]
More exception test https://github.com/BME-MIT-IET/anyapicifiai-iet-2019/commit/ddc84f2cd7106ff569fe3a398e1ed403afd09e0b

**Comment by mrdeakd** [comment]
new exception tests Commit : https://github.com/BME-MIT-IET/anyapicifiai-iet-2019/commit/6517646ed35103cc0f4542e2a626c00d8d2b7b93
