### ISSUE TITLE
Use Maven in the project

### ISSUE THREAD

**Issue by norbertgal97** [BME-MIT-IET/anyapicifiai-iet-2019#3]
We need better build automation tool than Ant Build.

**Comment by mrdeakd** [comment]
Commit : https://github.com/BME-MIT-IET/anyapicifiai-iet-2019/commit/3b1e50164f875546032ec9901c50de2b93fee7af 
Maven is in the system now. @norbertgal97

**Comment by norbertgal97** [comment]
I checked the pom.xml and the dependencies.
It's working.
