### ISSUE TITLE
Delete Ant lib folder

### ISSUE THREAD

**Issue by NomarCub** [BME-MIT-IET/anyapicifiai-iet-2019#4]
Delete unnecessary Ant dependencies

**Comment by mrdeakd** [comment]
You can delete the libs and the build.xml which is connected to ant. @NomarCub 
We finished the work with Maven.

**Comment by norbertgal97** [comment]
Commit: [a0a99a4](https://github.com/BME-MIT-IET/anyapicifiai-iet-2019/commit/a0a99a48265d97f073eab4903ac8a3c853b46ab1)

**Comment by norbertgal97** [comment]
Commit: [4fc4c8f](https://github.com/BME-MIT-IET/anyapicifiai-iet-2019/commit/4fc4c8ff0497e54b49bf31ca32968d71becb17a9)
build.xml removed
